### ISSUE TITLE
59 cartes lors de l'import

### ISSUE THREAD

**Issue by bryouf22** [annro-git/magic#22]
1 Merfolk Branchwalker
3 River Heralds' Boon
2 River Sneak
9 Island
11 Forest
3 Disperse
2 Sleep
4 Woodland Stream
1 Hinterland Harbor
1 Deeproot Elite
3 Jade Bearer
1 Jadelight Ranger
2 Jungleborn Pioneer
1 Kumena, Tyrant of Orazca
3 Merfolk Mistbinder
1 Seafloor Oracle
3 Silvergill Adept
2 Tempest Caller
3 Watertrap Weaver
1 Herald of Secret Streams
3 Kumena's Speaker

**Comment by annro-git** [comment]
voir https://github.com/annro-git/magic/issues/28
